# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Byung-Il Oh
email: bioh.inbox@gmail.com
description: Personal profile page of Byung-Il Oh # this means to ignore newlines until "url:"
footer_text: 
url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated
show_downloads: true

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: byungil-oh # your GitHub user name
twitter_username: byungil_oh # your Twitter handle
linkedin_username: byung-il-oh-aa0468156 # your LinkedIn user name
scholar_userid: 5X2clUkAAAAJ # your Google Scholar ID
orcid_id: 0000-0003-2359-9397 # your ORCID ID
contact_note: >
  Contact me at any time :)

google_analytics: UA-125812510-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed
    - jekyll/scholar
    - jemoji


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
